### ISSUE TITLE
Relay does not honor "limit" on filters

### ISSUE THREAD

**Issue by Giszmo** [atdixon/me.untethr.nostr-relay#1]
According to nip-01,

```
["REQ","cn",{"authors":["46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184b16bd8ce4d"],"limit":10} ]
```

should return at max 10 events but it does return 386.

**Comment by atdixon** [comment]
https://github.com/nostr-protocol/nips/blob/master/01.md

**Comment by atdixon** [comment]
Implemented new filter `limit` property. And re-deployed known relay instance https://nostr-relay.untethr.me/

**Comment by atdixon** [comment]
Thanks for filing this issue!

**Comment by Giszmo** [comment]
Thanks for fixing it! ;)
