### ISSUE TITLE
Please support nip-15 "End of Stored Events"

### ISSUE THREAD

**Issue by Giszmo** [atdixon/me.untethr.nostr-relay#2]
It's helpful to detect when a relay is done with all stored events. In many cases the client would like to disconnect at that point but has to fall back to some timeout estimate of when no more events are expected.

**Comment by atdixon** [comment]
Reference: https://github.com/nostr-protocol/nips/blob/master/15.md

**Comment by atdixon** [comment]
Reference: https://github.com/nostr-protocol/nips/blob/master/15.md

**Comment by atdixon** [comment]
Implemented nip 15. And re-deployed known relay instance https://nostr-relay.untethr.me/

**Comment by atdixon** [comment]
Thanks for filing this issue!
