### ISSUE TITLE
Please support explicit filters for all events

### ISSUE THREAD

**Issue by Giszmo** [atdixon/me.untethr.nostr-relay#3]
Querying

```
["REQ","cn",{"since":0}]
```

returns 35710 events and keeps forwarding new events.

```
["REQ","cn",{}]
```

should do the same. It currently returns nothing and does not forward new events neither.

**Comment by vishalxl** [comment]
<img width="1280" alt="2022-08-29 (11)" src="https://user-images.githubusercontent.com/64505169/187180578-45306099-71fa-43d2-ad31-61570222c289.png">

Seeing same issue, where it is returning 35k events event when I've set limit to 200.

**Comment by Giszmo** [comment]
@vishalxl did you mean to reply to #1?

**Comment by vishalxl** [comment]
@Giszmo yes, sort of made mistake in posting it here. It belong there only, its almost the same error, its giving way more events than asked for.

**Comment by atdixon** [comment]
Fixed!
